import { useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import {
  SdkRequestError,
  adminCreateInventoryAdjustment,
  adminCreateInventoryLevel,
  adminCreateInventoryTransfer,
  adminDeleteInventoryLevel,
  adminListInventoryLevelsQueryKey,
  adminListInventoryTransactionsQueryKey,
  useAdminListInventoryItems,
} from '@repo/admin-sdk';
import type {
  CreateInventoryAdjustmentBody,
  CreateInventoryLevelBody,
  CreateInventoryTransferBody,
  DeleteInventoryLevelResult,
  InventoryAdjustmentResult,
  InventoryItemOption,
  InventoryLevelResult,
  InventoryTransferResult,
} from '@repo/types/admin';

// Query hooks are generated by the SDK. Local mutation wrappers keep toast and
// invalidation behavior close to the admin feature that owns the workflow.
export const inventoryLevelsQueryPrefix = adminListInventoryLevelsQueryKey();
export const inventoryTransactionsQueryPrefix = adminListInventoryTransactionsQueryKey();

export function useInventoryItemOptions() {
  return useAdminListInventoryItems<InventoryItemOption[]>(
    { pageSize: 200 },
    {
      query: {
        staleTime: 5 * 60 * 1000,
        select: (response) => response.data,
      },
    }
  );
}

export function useCreateInventoryLevel() {
  const queryClient = useQueryClient();

  return useMutation<InventoryLevelResult, SdkRequestError, CreateInventoryLevelBody>({
    mutationFn: async (body) => {
      const res = await adminCreateInventoryLevel(body);
      return res.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: inventoryLevelsQueryPrefix });
      toast.success('Inventory item assigned to stock location');
    },
    onError: (error) => {
      toast.error(error.message || 'Failed to assign inventory item');
    },
  });
}

export function useDeleteInventoryLevel() {
  const queryClient = useQueryClient();

  return useMutation<
    DeleteInventoryLevelResult,
    SdkRequestError,
    { inventoryItemId: string; locationId: string }
  >({
    mutationFn: async ({ inventoryItemId, locationId }) => {
      const res = await adminDeleteInventoryLevel(inventoryItemId, locationId);
      return res.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: inventoryLevelsQueryPrefix });
      toast.success('Inventory item removed from stock location');
    },
    onError: (error) => {
      toast.error(error.message || 'Failed to remove inventory item');
    },
  });
}

export function useCreateInventoryAdjustment() {
  const queryClient = useQueryClient();

  return useMutation<
    InventoryAdjustmentResult,
    SdkRequestError,
    CreateInventoryAdjustmentBody
  >({
    mutationFn: async (body) => {
      const res = await adminCreateInventoryAdjustment(body);
      return res.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: inventoryLevelsQueryPrefix });
      queryClient.invalidateQueries({ queryKey: inventoryTransactionsQueryPrefix });
      toast.success('Inventory adjusted');
    },
    onError: (error) => {
      toast.error(error.message || 'Failed to adjust inventory');
    },
  });
}

export function useCreateInventoryTransfer() {
  const queryClient = useQueryClient();

  return useMutation<
    InventoryTransferResult,
    SdkRequestError,
    CreateInventoryTransferBody
  >({
    mutationFn: async (body) => {
      const res = await adminCreateInventoryTransfer(body);
      return res.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: inventoryLevelsQueryPrefix });
      queryClient.invalidateQueries({ queryKey: inventoryTransactionsQueryPrefix });
      toast.success('Inventory transferred');
    },
    onError: (error) => {
      toast.error(error.message || 'Failed to transfer inventory');
    },
  });
}
