import { useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import {
  SdkRequestError,
  adminCreateInventoryAdjustment,
  adminListInventoryLevelsQueryKey,
  adminListInventoryTransactionsQueryKey,
} from '@repo/admin-sdk';
import type {
  CreateInventoryAdjustmentBody,
  InventoryAdjustmentResult,
} from '@repo/types/admin';

// Query hooks are generated by the SDK. Local mutation wrappers keep toast and
// invalidation behavior close to the admin feature that owns the workflow.
export const inventoryLevelsQueryPrefix = adminListInventoryLevelsQueryKey();
export const inventoryTransactionsQueryPrefix = adminListInventoryTransactionsQueryKey();

export function useCreateInventoryAdjustment() {
  const queryClient = useQueryClient();

  return useMutation<
    InventoryAdjustmentResult,
    SdkRequestError,
    CreateInventoryAdjustmentBody
  >({
    mutationFn: async (body) => {
      const res = await adminCreateInventoryAdjustment(body);
      return res.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: inventoryLevelsQueryPrefix });
      queryClient.invalidateQueries({ queryKey: inventoryTransactionsQueryPrefix });
      toast.success('Inventory adjusted');
    },
    onError: (error) => {
      toast.error(error.message || 'Failed to adjust inventory');
    },
  });
}
